distribution/urls.py
from django.urls import path
from . import views

app_name = "distribution"

urlpatterns = [
    path("allocate/<int:food_id>/", views.allocate_distribution, name='allocate_distribution'),
    path("list/", views.DistributionList.as_view(), name='list'),

    path("clear/<int:distribution_id>/", views.clear_distribution, name="clear"),
    path("cleared/pdf/generate/<int:distribution_id>/", views.cleared_distribution_pdf, name="cleared_pdf"),
]

food/urls.py
from django.urls import path
from . import views

app_name = "food"

urlpatterns = [
    path("create/", views.CreateFood.as_view(), name="create"),
    path("detail/<int:pk>/", views.FoodDetail.as_view(), name="detail"),
    path("list/", views.FoodList.as_view(), name="list"),
    path("update/<int:pk>/", views.UpdateFood.as_view(), name="update"),
    path("delete/<int:pk>/", views.DeleteFood.as_view(), name="delete"),
    path("delete/success.html", views.success_delete_food, name="success_delete"),

    path("deposit/<int:food_id>/", views.IncreaseReserves.as_view(), name='increase_reserves'),
    path("deposit/success/<int:food_id>/", views.success_increase_reserves, name='success_increase_reserve'),

    path('unit/list/', views.DistributionUnitList.as_view(), name='unit_list'),
    path('unit/detail/<int:pk>/', views.DistributionUnitDetail.as_view(), name='unit_detail'),
    path('unit/create/', views.CreateDistributionUnit.as_view(), name='unit_create'),
    path('unit/update/<int:id>/', views.UpdateDistributionUnit.as_view(), name='unit_update'),
    path('unit/delete/<int:pk>/', views.DeleteDistributionUnit.as_view(), name='unit_delete'),
    path('unit/delete/success.html', views.success_delete_food_unit, name='success_delete_unit')
]

refugee_system/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('account.urls')),
    path('food/', include('food.urls')),
    path('refugee/', include('refugee.urls')),
    path('distribution/', include('distribution.urls')),
]

distribution/models.py
from django.db import models
from refugee.models import Refugee
from food.models import Food
from django.utils import timezone


class Distribution(models.Model):
    refugee = models.ForeignKey(Refugee, on_delete=models.SET_NULL, null=True)
    food = models.ForeignKey(Food, on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField()
    allocation_time = models.DateTimeField(default=timezone.now)
    picking_time = models.DateTimeField(null=True, blank=True)
    status = models.BooleanField(default=False)

    class Meta:
        verbose_name = "Distribution"
        verbose_name_plural = "Distributions"
        permissions = (
            ("can_allocate_distribution", "Can allocate distribution"),
            ("can_clear_distribution", "Can clear distribution")
        )
        ordering = ("allocation_time", "picking_time")

    def __str__(self):
        if self.status:
            status_verbose = "Picked"
        else:
            status_verbose = "Unpicked"

        return "%s distribution to %s of %d %s" % (status_verbose, self.refugee.name, self.quantity, self.food.name)

distribution/views.py
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from django.http import HttpResponse
from food.models import Food
from django.views.generic import ListView
from refugee.models import Refugee
from .models import Distribution
from refugee_system.utils import render_template_to_pdf
import math


# Create your views here.
def allocate_distribution(request, *args, **kwargs):
    food = get_object_or_404(Food, id=kwargs.get("food_id"))
    quantity_rem = food.quantity
    quantity_dist_ttl = 0.75 * quantity_rem
    refugees = Refugee.objects.all()
    quantity_per_refugee = math.floor(quantity_dist_ttl / refugees.count())
    if quantity_per_refugee <= 0:
        context = {
            "food": food,
            "quantity_rem": quantity_rem,
            "refugees_count": refugees.count()
        }
        return render(request=request, template_name='distribution/distribution_allocation_failed_insufficient.html',
                      context=context)
    else:
        [Distribution.objects.create(refugee=refugee, quantity=quantity_per_refugee, food=food).save() for refugee in
         refugees]
        context = {
            "food": food,
            "quantity_per_refugee": quantity_per_refugee,
            "num_refugees": refugees.count()
        }
        return render(request=request, template_name='distribution/distribution_allocation_success.html',
                      context=context)


class DistributionList(ListView):
    model = Distribution
    queryset = Distribution.objects.filter(status=False)
    template_name = 'distribution/distribution_list.html'


def clear_distribution(request, *args, **kwargs):
    distribution = Distribution.objects.get(id=kwargs["distribution_id"])
    distribution.status = True
    distribution.picking_time = timezone.now()
    distribution.save()
    food = distribution.food
    food.quantity -= distribution.quantity
    food.save()
    context = {
        "distribution":distribution,
    }
    return render(request, 'distribution/distribution_cleared_successfully.html', context)


def cleared_distribution_pdf(request, *args, **kwargs):
    distribution = Distribution.objects.get(id=kwargs["distribution_id"])
    context = {
        "distribution": distribution,
    }
    pdf = render_template_to_pdf('distribution/distribution_clearance_pdf.html', context)
    return HttpResponse(pdf, content_type='application/pdf')

templates/distribution/distribution_allocation_failed_insufficient.html
{% extends 'base_messages.html' %}

{% block content %}
<h1 class="tx-100 tx-xs-140 tx-normal tx-inverse tx-roboto mg-b-0">Failed!</h1>
<h5 class="tx-xs-24 tx-normal tx-info mg-b-30 lh-5">Distribution allocation for food {{ food }} has failed due to insufficient quantity ({{ quantity_rem }}) in reserves for {{ refugees_count }} refugee(s).</h5>

<div class="d-flex justify-content-center">
    <div class="input-group wd-xs-300">
        <a href="{% url 'food:list' %}"><button class="btn btn-warning btn-block">Click here to go back to food list.</button></a>
    </div><!-- input-group -->
</div><!-- d-flex -->
{% endblock %}

templates/distribution/distribution_allocation_success.html
{% extends 'base_messages.html' %}

{% block content %}
<h1 class="tx-100 tx-xs-140 tx-normal tx-inverse tx-roboto mg-b-0">Success!</h1>
<h5 class="tx-xs-24 tx-normal tx-info mg-b-30 lh-5">Food distribution has been successfully allocated.</h5>

<div class="d-flex justify-content-center">
    <div class="input-group wd-xs-300">
        <a href="{% url 'distribution:list' %}"><button class="btn btn-info btn-block">Click here to view uncleared distributions.</button></a>
    </div><!-- input-group -->
</div><!-- d-flex -->
{% endblock %}

templates/distribution/distribution_clearance_pdf.html
<html>
<head>
    <title>Distribution to {{ distribution.refugee.name }}</title>
</head>
<body>
    <h3>Distribution to {{ distribution.refugee.name }}</h3>
    <table>
        <tr>
            <td>Refugee Name</td>
            <td>{{ distribution.refugee.name }}</td>
        </tr>
        <tr>
            <td>Date Allocated</td>
            <td>{{ distribution.allocation_time | date }}</td>
        </tr>
        <tr>
            <td>Food</td>
            <td>{{ distribution.food.name }}</td>
        </tr>
        <tr>
            <td>Quantity</td>
            <td>{{ distribution.quantity }} {{ distribution.food.unit.abbreviation }}</td>
        </tr>
        <tr>
            <td>Expected Picking Date</td>
            <td>{{ distribution.picking_time|date }}</td>
        </tr>
    </table>
</body>
</html>

templates/distribution/distribution_cleared_successfully.html
{% extends 'base_messages.html' %}

{% block content %}
<h1 class="tx-100 tx-xs-140 tx-normal tx-inverse tx-roboto mg-b-0">Success!</h1>
<h5 class="tx-xs-24 tx-normal tx-info mg-b-30 lh-5">Food distribution has been cleared to refugee {{ distribution.refugee.name }} on {{ distribution.picking_time }} successfully. He or she may proceed to store.</h5>

<div class="d-flex justify-content-center">
    <div class="input-group wd-xs-300">
        <a href="{% url 'distribution:list' %}" target="_blank"><button class="btn btn-info btn-block">Click here to go back to distribution list.</button></a>
    </div><!-- input-group -->
    <div class="input-group wd-xs-300">
        <a href="{% url 'distribution:cleared_pdf' distribution.id %}"><button class="btn btn-info btn-block">Click here to print pdf.</button></a>
    </div><!-- input-group -->
</div><!-- d-flex -->
{% endblock %}

templates/distribution/distribution_list.html
{% extends 'base_dashboard.html' %}
{% load static %}

{% block content %}
<div class="br-mainpanel">
  <div class="br-pageheader pd-y-15 pd-l-20">
    <nav class="breadcrumb pd-0 mg-0 tx-12">{{ site_title }} / Distribution / List</nav>
  </div><!-- br-pageheader -->
  <div class="d-sm-flex align-items-center pd-t-15 pd-sm-t-25 pd-x-20 pd-sm-x-30">
    <i class="icon ion-ios-filing-outline tx-70 lh-0 tx-gray-800"></i>
    <div class="pd-sm-l-20">
      <h4 class="tx-gray-800 mg-b-5">Distribution List</h4>
    </div>
  </div><!-- d-flex -->

  <div class="br-pagebody">
    <!-- this is where your contents will be added -->
      <div class="br-section-wrapper">
        <h6 class="tx-gray-800 tx-uppercase tx-bold tx-14 mg-b-10">Unpicked Distributions</h6>
          <div class="table-wrapper">
            <table id="datatable1" class="table display responsive nowrap">
              <thead>
                <tr>
                  <th class="wd-15p">Actions</th>
                  <th class="wd-15p">Refugee Name</th>
                  <th class="wd-15p">Food Name</th>
                  <th class="wd-20p">Quantity to be Allocated</th>
                  <th class="wd-15p">Date Allocated</th>
                </tr>
              </thead>
              <tbody>

              {% for distribution in distribution_list %}
              <tr>
                  <th class="wd-15p"><a href="{% url 'distribution:clear' distribution.id %}"> <span class="fa fa-clipboard"></span> Clear</a> </th>
                  <th class="wd-15p">{{ distribution.refugee.name }}</th>
                  <th class="wd-15p">{{ distribution.food.name }}</th>
                  <th class="wd-20p">{{ distribution.quantity }}</th>
                  <th class="wd-15p">{{ distribution.allocation_time }}</th>

                </tr>
              {% endfor %}

              </tbody>
                <thead>
                <tr>
                  <th class="wd-15p">Actions</th>
                  <th class="wd-15p">Refugee Name</th>
                  <th class="wd-15p">Food Name</th>
                  <th class="wd-20p">Quantity to be Allocated</th>
                  <th class="wd-15p">Date Allocated</th>
                </tr>
              </thead>
            </table>
        </div>
      </div>
  </div><!-- br-pagebody -->

</div><!-- br-mainpanel -->
{% endblock %}

{% block scripts %}
    <script type="text/javascript" src="{% static "lib/datatables/jquery.dataTables.js" %}"></script>
    <script type="text/javascript" src="{% static 'lib/datatables-responsive/dataTables.responsive.js' %}"></script>
<script type="text/javascript">
$('#datatable1').DataTable({
  responsive: true,
  language: {
    searchPlaceholder: 'Search...',
    sSearch: '',
    lengthMenu: '_MENU_ items/page',
  }
});
</script>
{% endblock %}