distribution/urls.py
from django.urls import path
from . import views

app_name = "distribution"

urlpatterns = [
    path("allocate/<int:food_id>/", views.allocate_distribution, name='allocate_distribution'),
    path("list/", views.DistributionList.as_view(), name='list'),

    path("clear/<int:distribution_id>/", views.clear_distribution, name="clear"),
    path("cleared/pdf/generate/<int:distribution_id>/", views.cleared_distribution_pdf, name="cleared_pdf"),
]

food/urls.py
from django.urls import path
from . import views

app_name = "food"

urlpatterns = [
    path("create/", views.CreateFood.as_view(), name="create"),
    path("detail/<int:pk>/", views.FoodDetail.as_view(), name="detail"),
    path("list/", views.FoodList.as_view(), name="list"),
    path("update/<int:pk>/", views.UpdateFood.as_view(), name="update"),
    path("delete/<int:pk>/", views.DeleteFood.as_view(), name="delete"),
    path("delete/success.html", views.success_delete_food, name="success_delete"),

    path("deposit/<int:food_id>/", views.IncreaseReserves.as_view(), name='increase_reserves'),
    path("deposit/success/<int:food_id>/", views.success_increase_reserves, name='success_increase_reserve'),

    path('unit/list/', views.DistributionUnitList.as_view(), name='unit_list'),
    path('unit/detail/<int:pk>/', views.DistributionUnitDetail.as_view(), name='unit_detail'),
    path('unit/create/', views.CreateDistributionUnit.as_view(), name='unit_create'),
    path('unit/update/<int:id>/', views.UpdateDistributionUnit.as_view(), name='unit_update'),
    path('unit/delete/<int:pk>/', views.DeleteDistributionUnit.as_view(), name='unit_delete'),
    path('unit/delete/success.html', views.success_delete_food_unit, name='success_delete_unit')
]

refugee_system/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('account.urls')),
    path('food/', include('food.urls')),
    path('refugee/', include('refugee.urls')),
    path('distribution/', include('distribution.urls')),
]

food/models.py
from django.db import models
from django.urls import reverse_lazy
from refugee_system.ModelMixins import ModelMixin


# Create your models here.
class DistributionUnit(ModelMixin, models.Model):
    name = models.CharField(max_length=50, verbose_name="Unit Name")
    abbreviation = models.CharField(max_length=5, verbose_name="Abbreviation")
    description = models.TextField(verbose_name="Unit Description")

    def __str__(self):
        return self.name

    class Meta(object):
        verbose_name = "Distribution Unit"
        verbose_name_plural = "Distribution Units"
        ordering = ("name",)
        permissions = (
            ("custom_can_add_food_unit", "Custom Can add Food Unit"),
            ("custom_can_delete_food_unit", "Custom Can delete Food Unit"),
            ("custom_can_update_food_unit", "Custom can update Food Unit")
        )

    def get_absolute_url(self):
        return reverse_lazy('food:unit_detail', kwargs={"pk":self.pk})


class Food(ModelMixin, models.Model):
    name = models.CharField(max_length=50, verbose_name="Food Name")
    description = models.TextField(verbose_name="Food Description or Remarks")
    unit = models.ForeignKey(DistributionUnit, on_delete=models.SET_NULL, null=True, verbose_name="Distribution Units")
    quantity = models.IntegerField(verbose_name="Quantity_available", default=0)

    def get_absolute_url(self):
        return reverse_lazy("food:detail" , kwargs={"pk": self.pk})

    def __str__(self):
        return self.name

    class Meta(object):
        verbose_name = "Food"
        verbose_name_plural = "Food"
        ordering = ("name",)
        permissions = (
            ("custom_can_add_food", "Custom Can add Food"),
            ("custom_can_delete_food", "Custom Can delete Food"),
            ("custom_can_update_food", "Custom can update Food")
        )

food/forms.py
from django import forms
from . models import Food


class IncreaseReservesForm(forms.Form):
    quantity = forms.IntegerField(required=True)

    def increase_reserves(self, food: Food):
        quantity = self.data['quantity']
        food.quantity += int(quantity)
        food.save()
        return True

food/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Food, DistributionUnit
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from .forms import IncreaseReservesForm


# Create your views here.
class CreateFood(LoginRequiredMixin, CreateView):
    model = Food
    template_name = "food/food_create_form.html"
    fields = ("name", "description", "unit")


class FoodList(ListView):
    model = Food
    template_name = 'food/food_list.html'


class FoodDetail(DetailView):
    model = Food
    template_name = 'food/food_detail.html'


class UpdateFood(LoginRequiredMixin, UpdateView):
    model = Food
    template_name = 'food/update_food_form.html'


class DeleteFood(LoginRequiredMixin,DeleteView):
    model = Food
    success_url = reverse_lazy("food:success_delete")


@login_required
def success_delete_food(request):
    return render(request, 'food/success_delete_food.html')


class IncreaseReserves(View):
    def get(self, *args, **kwargs):
        form = IncreaseReservesForm()
        food = get_object_or_404(Food, id=self.kwargs.get("food_id"))
        context = {"food":food, "form":form}
        return render(self.request, "food/increase_reserves_form.html", context)

    def post(self, *args, **kwargs):
        form = IncreaseReservesForm(data=self.request.POST)
        food = get_object_or_404(Food, id=self.kwargs.get("food_id"))
        if form.is_valid():
            form.increase_reserves(food)
            return redirect(reverse_lazy("food:success_increase_reserve", kwargs={"food_id": food.id}))
        else:
            context = {"food": food, "form": form}
            return render(self.request, "food/increase_reserves_form.html", context)


@login_required
def success_increase_reserves(request, *args, **kwargs):
    food = get_object_or_404(Food, id=kwargs["food_id"])
    context = {
        "food": food
    }
    return render(request, "food/success_increase_reserves.html", context)


class CreateDistributionUnit(CreateView):
    model = DistributionUnit
    template_name = 'distribution_unit/create_form.html'
    fields = ("name", "abbreviation", "description")


class UpdateDistributionUnit(UpdateView) :
    model = DistributionUnit
    template_name = 'distribution_unit/update_form.html'
    fields = ("name", "abbreviation", "description")


class DeleteDistributionUnit(DeleteView) :
    model = DistributionUnit
    success_url = reverse_lazy('food:success_delete_unit')


@login_required
def success_delete_food_unit(request):
    return render(request, 'food/success_delete_food.html')


class DistributionUnitList(ListView) :
    model = DistributionUnit
    template_name = 'distribution_unit/list.html'


class DistributionUnitDetail(DetailView) :
    model = DistributionUnit
    template_name = 'distribution_unit/detail.html'

templates/food/food_create_form.html
{% extends 'base_dashboard.html' %}

{% load widget_tweaks %}
{% load static %}

{% block content %}
<div class="br-mainpanel">
  <div class="br-pageheader pd-y-15 pd-l-20">
    <nav class="breadcrumb pd-0 mg-0 tx-12">{{ site_title }} / Food / Add New</nav>
  </div><!-- br-pageheader -->
  <div class="d-sm-flex align-items-center pd-t-15 pd-sm-t-25 pd-x-20 pd-sm-x-30">
    <i class="icon ion-ios-filing-outline tx-70 lh-0 tx-gray-800"></i>
    <div class="pd-sm-l-20">
      <h4 class="tx-gray-800 mg-b-5">Add Food</h4>
      <p class="mg-b-0">Register new food</p>
    </div>
  </div><!-- d-flex -->

  <div class="br-pagebody">
    <!-- this is where your contents will be added -->
      <form method="post" action="{% url 'food:create' %}" class="form">
        {% csrf_token %}
        {% for hidden_field in form.hidden_field  %}
            <span class="text-warning">{{ hidden_field.errors|safe }}</span>
            {{ hidden_field }}
        {% endfor %}
        {% for visible_field in form.visible_fields %}
            <div class="form-group">
                {{ visible_field.label_tag }}
                {{ visible_field }}
                {% if visible_field.help_text %}
                    <span class="text-info">{{ visible_field.help_text|safe }}</span>
                {% endif %}
                {% if visible_field.errors %}
                    <span class="text-warning">{{ visible_field.errors|safe }}</span>
                {% endif %}
            </div><!-- form-group -->
        {% endfor %}
        <button type="submit" class="btn btn-info">Create Food</button>
      <span class="pull-right"><button type="reset" class="btn btn-warning">Reset</button></span>
    </form>
  </div><!-- br-pagebody -->

</div><!-- br-mainpanel -->
{% endblock %}

{% block scripts %}

    <script type="text/javascript" src="{% static 'lib/select2/js/select2.min.js' %}"></script>
    <script type="text/javascript">
        $("select").addClass("form-control select2");
        $("input").addClass("form-control");
    </script>

{% endblock %}

templates/food/food_detail.html
{% extends 'base_dashboard.html' %}
{% load static %}

{% block content %}
<div class="br-mainpanel">
  <div class="br-pageheader pd-y-15 pd-l-20">
    <nav class="breadcrumb pd-0 mg-0 tx-12">{{ site_title }} / Food / Details</nav>
  </div><!-- br-pageheader -->
  <div class="d-sm-flex align-items-center pd-t-15 pd-sm-t-25 pd-x-20 pd-sm-x-30">
    <i class="icon ion-ios-filing-outline tx-70 lh-0 tx-gray-800"></i>
    <div class="pd-sm-l-20">
      <h4 class="tx-gray-800 mg-b-5">Food Details</h4>
    </div>
  </div><!-- d-flex -->

  <div class="br-pagebody">
    <!-- this is where your contents will be added -->
      <div class="br-section-wrapper">
        <h6 class="tx-gray-800 tx-uppercase tx-bold tx-14 mg-b-10">Details for {{ food.name }}</h6>
          <div id="accordion" class="accordion" role="tablist" aria-multiselectable="true">
          {% for name, value in food.get_fields %}
          <div class="card">
                <div class="card-header" role="tab" id="headingOne">
                    <h6 class="mg-b-0">
                        <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne" class="tx-gray-800 transition">
                            {{ name|title }}
                        </a>
                    </h6>
                </div><!-- card-header -->

                <div id="collapseOne" class="collapse show" role="tabpanel" aria-labelledby="headingOne">
                    <div class="card-block pd-20">
                        {{ value|capfirst }}
                    </div>
                </div>
            </div><!-- card -->
          {% endfor %}
            <!-- ADD MORE CARD HERE -->
          </div><!-- accordion -->
      </div>
  </div><!-- br-pagebody -->

</div><!-- br-mainpanel -->
{% endblock %}

{% block scripts %}

{% endblock %}

templates/food/food_list.html
{% extends 'base_dashboard.html' %}
{% load static %}

{% block content %}
<div class="br-mainpanel">
  <div class="br-pageheader pd-y-15 pd-l-20">
    <nav class="breadcrumb pd-0 mg-0 tx-12">{{ site_title }} / Food / List</nav>
  </div><!-- br-pageheader -->
  <div class="d-sm-flex align-items-center pd-t-15 pd-sm-t-25 pd-x-20 pd-sm-x-30">
    <i class="icon ion-ios-filing-outline tx-70 lh-0 tx-gray-800"></i>
    <div class="pd-sm-l-20">
      <h4 class="tx-gray-800 mg-b-5">Food List</h4>
      <p class="mg-b-0">Add, Update and Delete Food items</p>
    </div>
  </div><!-- d-flex -->

  <div class="br-pagebody">
    <!-- this is where your contents will be added -->
      <div class="br-section-wrapper">
        <h6 class="tx-gray-800 tx-uppercase tx-bold tx-14 mg-b-10">List of Foods</h6>
          <div style="padding-bottom: inherit ">
              <a href="{% url 'food:create' %}"><button class="btn btn-info">Add Food</button></a>
          </div>
          <div class="table-wrapper">
            <table id="datatable1" class="table display responsive nowrap">
              <thead>
                <tr>
                  <th class="wd-15p">Name</th>
                  <th class="wd-15p">Distribution Unit</th>
                  <th class="wd-20p">Quantity in Stock</th>
                  <th class="wd-15p">Remarks</th>
                  <th class="wd-15p">Actions</th>
                </tr>
              </thead>
              <tbody>

              {% for food in food_list %}
              <tr>
                  <th class="wd-15p">{{ food.name }}</th>
                  <th class="wd-15p">{{ food.unit }}</th>
                  <th class="wd-20p">{{ food.quantity }}</th>
                  <th class="wd-15p">{{ food.description }}</th>
                  <th class="wd-15p">
                      <a href="{% url 'food:increase_reserves' food.id %}">Increase Reserves</a> |
                      <a href="{% url 'distribution:allocate_distribution' food.id %}">Allocate</a>
                  </th>
                </tr>
              {% endfor %}

              </tbody>
                <thead>
                <tr>
                  <th class="wd-15p">Name</th>
                  <th class="wd-15p">Distribution Unit</th>
                  <th class="wd-20p">Quantity in Stock</th>
                  <th class="wd-15p">Remarks</th>
                  <th class="wd-15p">Actions</th>
                </tr>
              </thead>
            </table>
        </div>
      </div>
  </div><!-- br-pagebody -->

</div><!-- br-mainpanel -->
{% endblock %}

{% block scripts %}
    <script type="text/javascript" src="{% static "lib/datatables/jquery.dataTables.js" %}"></script>
    <script type="text/javascript" src="{% static 'lib/datatables-responsive/dataTables.responsive.js' %}"></script>
<script type="text/javascript">
$('#datatable1').DataTable({
  responsive: true,
  language: {
    searchPlaceholder: 'Search...',
    sSearch: '',
    lengthMenu: '_MENU_ items/page',
  }
});
</script>
{% endblock %}

templates/food/increase_reserves_form.html
{% extends 'base_dashboard.html' %}

{% load widget_tweaks %}
{% load static %}

{% block content %}
<div class="br-mainpanel">
  <div class="br-pageheader pd-y-15 pd-l-20">
    <nav class="breadcrumb pd-0 mg-0 tx-12">{{ site_title }} / Food / Increase Reserves</nav>
  </div><!-- br-pageheader -->
  <div class="d-sm-flex align-items-center pd-t-15 pd-sm-t-25 pd-x-20 pd-sm-x-30">
    <i class="icon ion-ios-filing-outline tx-70 lh-0 tx-gray-800"></i>
    <div class="pd-sm-l-20">
      <h4 class="tx-gray-800 mg-b-5">Add Food Reserves</h4>
    </div>
  </div><!-- d-flex -->

  <div class="br-pagebody">
    <!-- this is where your contents will be added -->
      <form method="post" action="{% url 'food:increase_reserves' food.id %}" class="form-inline">
        {% csrf_token %}
        {% for hidden_field in form.hidden_field  %}
            <span class="text-warning">{{ hidden_field.errors|safe }}</span>
            {{ hidden_field }}
        {% endfor %}
        {% for visible_field in form.visible_fields %}
            <div class="form-group">
                {{ visible_field.label_tag }}
                {{ visible_field }}
                {% if visible_field.help_text %}
                    <span class="text-info">{{ visible_field.help_text|safe }}</span>
                {% endif %}
                {% if visible_field.errors %}
                    <span class="text-warning">{{ visible_field.errors|safe }}</span>
                {% endif %}
            </div><!-- form-group -->
        {% endfor %}
        <br>
        <button type="submit" class="btn btn-info">Update Food Reserves</button>
      <span class="pull-right"><button type="reset" class="btn btn-warning">Reset</button></span>
    </form>
  </div><!-- br-pagebody -->

</div><!-- br-mainpanel -->
{% endblock %}

{% block scripts %}

    <script type="text/javascript" src="{% static 'lib/select2/js/select2.min.js' %}"></script>
    <script type="text/javascript">
        $("select").addClass("form-control select2");
        $("input").addClass("form-control");
    </script>

{% endblock %}

templates/food/success_delete_food.html
{% extends 'base_messages.html' %}

{% block content %}
<h1 class="tx-100 tx-xs-140 tx-normal tx-inverse tx-roboto mg-b-0">Success!</h1>
<h5 class="tx-xs-24 tx-normal tx-info mg-b-30 lh-5">Food has been successfully deleted.</h5>

<div class="d-flex justify-content-center">
    <div class="input-group wd-xs-300">
        <a href="{% url 'food:list' %}"><button class="btn btn-info btn-block">Click here to go back to food list.</button></a>
    </div><!-- input-group -->
</div><!-- d-flex -->
{% endblock %}

templates/food/success_increase_reserves.html
{% extends 'base_messages.html' %}

{% block content %}
<h1 class="tx-100 tx-xs-140 tx-normal tx-inverse tx-roboto mg-b-0">Success!</h1>
<h5 class="tx-xs-24 tx-normal tx-info mg-b-30 lh-5">Food reserve has been successfully increased.</h5>

<div class="d-flex justify-content-center">
    <div class="input-group wd-xs-300">
        <a href="{% url 'food:detail' food.id %}"><button class="btn btn-info btn-block">Click here to view food {{ food.name }} details.</button></a>
    </div><!-- input-group -->
</div><!-- d-flex -->
{% endblock %}

templates/food/update_food_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>