food/urls.py
from django.urls import path
from . import views

app_name = "food"

urlpatterns = [
    path("create/", views.CreateFood.as_view(), name="create"),
    path("detail/<int:pk>/", views.FoodDetail.as_view(), name="detail"),
    path("list/", views.FoodList.as_view(), name="list"),
    path("update/<int:pk>/", views.UpdateFood.as_view(), name="update"),
    path("delete/<int:pk>/", views.DeleteFood.as_view(), name="delete"),
    path("delete/success.html", views.success_delete_food, name="success_delete"),

    path("deposit/<int:food_id>/", views.IncreaseReserves.as_view(), name='increase_reserves'),
    path("deposit/success/<int:food_id>/", views.success_increase_reserves, name='success_increase_reserve'),

    path('unit/list/', views.DistributionUnitList.as_view(), name='unit_list'),
    path('unit/detail/<int:pk>/', views.DistributionUnitDetail.as_view(), name='unit_detail'),
    path('unit/create/', views.CreateDistributionUnit.as_view(), name='unit_create'),
    path('unit/update/<int:id>/', views.UpdateDistributionUnit.as_view(), name='unit_update'),
    path('unit/delete/<int:pk>/', views.DeleteDistributionUnit.as_view(), name='unit_delete'),
    path('unit/delete/success.html', views.success_delete_food_unit, name='success_delete_unit')
]

refugee_system/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('account.urls')),
    path('food/', include('food.urls')),
    path('refugee/', include('refugee.urls')),
    path('distribution/', include('distribution.urls')),
]

templates/distribution_unit/create_form.html
{% extends 'base_dashboard.html' %}

{% load widget_tweaks %}
{% load static %}

{% block content %}
<div class="br-mainpanel">
  <div class="br-pageheader pd-y-15 pd-l-20">
    <nav class="breadcrumb pd-0 mg-0 tx-12">{{ site_title }} / Food / Add New</nav>
  </div><!-- br-pageheader -->
  <div class="d-sm-flex align-items-center pd-t-15 pd-sm-t-25 pd-x-20 pd-sm-x-30">
    <i class="icon ion-ios-filing-outline tx-70 lh-0 tx-gray-800"></i>
    <div class="pd-sm-l-20">
      <h4 class="tx-gray-800 mg-b-5">Add Food Unit</h4>
      <p class="mg-b-0">Register new food distribution unit</p>
    </div>
  </div><!-- d-flex -->

  <div class="br-pagebody">
    <!-- this is where your contents will be added -->
      <form method="post" action="{% url 'food:unit_create' %}" class="form">
        {% csrf_token %}
        {% for hidden_field in form.hidden_field  %}
            <span class="text-warning">{{ hidden_field.errors|safe }}</span>
            {{ hidden_field }}
        {% endfor %}
        {% for visible_field in form.visible_fields %}
            <div class="form-group">
                {{ visible_field.label_tag }}
                {{ visible_field }}
                {% if visible_field.help_text %}
                    <span class="text-info">{{ visible_field.help_text|safe }}</span>
                {% endif %}
                {% if visible_field.errors %}
                    <span class="text-warning">{{ visible_field.errors|safe }}</span>
                {% endif %}
            </div><!-- form-group -->
        {% endfor %}
        <button type="submit" class="btn btn-info">Create Food Unit</button>
      <span class="pull-right"><button type="reset" class="btn btn-warning">Reset</button></span>
    </form>
  </div><!-- br-pagebody -->

</div><!-- br-mainpanel -->
{% endblock %}

{% block scripts %}

    <script type="text/javascript" src="{% static 'lib/select2/js/select2.min.js' %}"></script>
    <script type="text/javascript">
        $("select").addClass("form-control select2");
        $("input").addClass("form-control");
    </script>

{% endblock %}

templates/distribution_unit/detail.html
{% extends 'base_dashboard.html' %}
{% load static %}

{% block content %}
<div class="br-mainpanel">
  <div class="br-pageheader pd-y-15 pd-l-20">
    <nav class="breadcrumb pd-0 mg-0 tx-12">{{ site_title }} / Food / Details</nav>
  </div><!-- br-pageheader -->
  <div class="d-sm-flex align-items-center pd-t-15 pd-sm-t-25 pd-x-20 pd-sm-x-30">
    <i class="icon ion-ios-filing-outline tx-70 lh-0 tx-gray-800"></i>
    <div class="pd-sm-l-20">
      <h4 class="tx-gray-800 mg-b-5">Distribution Unit Details</h4>
    </div>
  </div><!-- d-flex -->

  <div class="br-pagebody">
    <!-- this is where your contents will be added -->
      <div class="br-section-wrapper">
        <h6 class="tx-gray-800 tx-uppercase tx-bold tx-14 mg-b-10">Details for {{ distributionunit.name }}</h6>
          <div id="accordion" class="accordion" role="tablist" aria-multiselectable="true">
          {% for name, value in distributionunit.get_fields %}
          <div class="card">
                <div class="card-header" role="tab" id="headingOne">
                    <h6 class="mg-b-0">
                        <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne" class="tx-gray-800 transition">
                            {{ name|title }}
                        </a>
                    </h6>
                </div><!-- card-header -->

                <div id="collapseOne" class="collapse show" role="tabpanel" aria-labelledby="headingOne">
                    <div class="card-block pd-20">
                        {{ value|capfirst }}
                    </div>
                </div>
            </div><!-- card -->
          {% endfor %}
            <!-- ADD MORE CARD HERE -->
          </div><!-- accordion -->
      </div>
  </div><!-- br-pagebody -->

</div><!-- br-mainpanel -->
{% endblock %}

{% block scripts %}

{% endblock %}

templates/distribution_unit/list.html
{% extends 'base_dashboard.html' %}
{% load static %}

{% block content %}
<div class="br-mainpanel">
  <div class="br-pageheader pd-y-15 pd-l-20">
    <nav class="breadcrumb pd-0 mg-0 tx-12">{{ site_title }} / Food / List</nav>
  </div><!-- br-pageheader -->
  <div class="d-sm-flex align-items-center pd-t-15 pd-sm-t-25 pd-x-20 pd-sm-x-30">
    <i class="icon ion-ios-filing-outline tx-70 lh-0 tx-gray-800"></i>
    <div class="pd-sm-l-20">
      <h4 class="tx-gray-800 mg-b-5">Distribution Unit List</h4>
      <p class="mg-b-0">Add, Update and Delete Food Distribution Unit items</p>
    </div>
  </div><!-- d-flex -->

  <div class="br-pagebody">
    <!-- this is where your contents will be added -->
      <div class="br-section-wrapper">
        <h6 class="tx-gray-800 tx-uppercase tx-bold tx-14 mg-b-10">List of Food Units</h6>
          <div style="padding-bottom: inherit ">
              <a href="{% url 'food:unit_create' %}"><button class="btn btn-info">Add Food Distribution Unit</button></a>
          </div>
          <div class="table-wrapper">
            <table id="datatable1" class="table display responsive nowrap">
              <thead>
                <tr>
                  <th class="wd-15p">Name</th>
                  <th class="wd-15p">Abbreviation</th>
                  <th class="wd-20p">Description/ Remarks</th>
                </tr>
              </thead>
              <tbody>
              {% for distributionunit in distributionunit_list %}
              <tr>
                  <th class="wd-15p">{{ distributionunit.name }}</th>
                  <th class="wd-15p">{{ distributionunit.abbreviation }}</th>
                  <th class="wd-20p">{{ distributionunit.description }}</th>
                </tr>
              {% endfor %}

              </tbody>
                <thead>
                <tr>
                  <th class="wd-15p">Name</th>
                  <th class="wd-15p">Abbreviation</th>
                  <th class="wd-20p">Description/ Remarks</th>
                </tr>
              </thead>
            </table>
        </div>
      </div>
  </div><!-- br-pagebody -->

</div><!-- br-mainpanel -->
{% endblock %}

{% block scripts %}
    <script type="text/javascript" src="{% static "lib/datatables/jquery.dataTables.js" %}"></script>
    <script type="text/javascript" src="{% static 'lib/datatables-responsive/dataTables.responsive.js' %}"></script>
<script type="text/javascript">
$('#datatable1').DataTable({
  responsive: true,
  language: {
    searchPlaceholder: 'Search...',
    sSearch: '',
    lengthMenu: '_MENU_ items/page',
  }
});
</script>
{% endblock %}

templates/distribution_unit/success_delete.html
{% extends 'base_messages.html' %}

{% block content %}
<h1 class="tx-100 tx-xs-140 tx-normal tx-inverse tx-roboto mg-b-0">Success!</h1>
<h5 class="tx-xs-24 tx-normal tx-info mg-b-30 lh-5">Food Distribution Unit has been successfully deleted.</h5>

<div class="d-flex justify-content-center">
    <div class="input-group wd-xs-300">
        <a href="{% url 'food:list' %}"><button class="btn btn-info btn-block">Click here to go back to food distribution unit list.</button></a>
    </div><!-- input-group -->
</div><!-- d-flex -->
{% endblock %}

templates/distribution_unit/update_form.html
{% extends 'base_dashboard.html' %}

{% load widget_tweaks %}
{% load static %}

{% block content %}
<div class="br-mainpanel">
  <div class="br-pageheader pd-y-15 pd-l-20">
    <nav class="breadcrumb pd-0 mg-0 tx-12">{{ site_title }} / Food / Add New</nav>
  </div><!-- br-pageheader -->
  <div class="d-sm-flex align-items-center pd-t-15 pd-sm-t-25 pd-x-20 pd-sm-x-30">
    <i class="icon ion-ios-filing-outline tx-70 lh-0 tx-gray-800"></i>
    <div class="pd-sm-l-20">
      <h4 class="tx-gray-800 mg-b-5">UpdateFood Unit</h4>
      <p class="mg-b-0">Update distribution unit</p>
    </div>
  </div><!-- d-flex -->

  <div class="br-pagebody">
    <!-- this is where your contents will be added -->
      <form method="post" action="{% url 'food:unit_update' %}" class="form">
        {% csrf_token %}
        {% for hidden_field in form.hidden_field  %}
            <span class="text-warning">{{ hidden_field.errors|safe }}</span>
            {{ hidden_field }}
        {% endfor %}
        {% for visible_field in form.visible_fields %}
            <div class="form-group">
                {{ visible_field.label_tag }}
                {{ visible_field }}
                {% if visible_field.help_text %}
                    <span class="text-info">{{ visible_field.help_text|safe }}</span>
                {% endif %}
                {% if visible_field.errors %}
                    <span class="text-warning">{{ visible_field.errors|safe }}</span>
                {% endif %}
            </div><!-- form-group -->
        {% endfor %}
        <button type="submit" class="btn btn-info">Update Food Unit</button>
      <span class="pull-right"><button type="reset" class="btn btn-warning">Reset</button></span>
    </form>
  </div><!-- br-pagebody -->

</div><!-- br-mainpanel -->
{% endblock %}

{% block scripts %}

    <script type="text/javascript" src="{% static 'lib/select2/js/select2.min.js' %}"></script>
    <script type="text/javascript">
        $("select").addClass("form-control select2");
        $("input").addClass("form-control");
    </script>

{% endblock %}