account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('register/', views.RegisterUser.as_view(), name='register_user'),
    path('register/success.html', views.success_user_create, name='register_success'),

    path('profile/', views.profile, name='profile'),
    path('profile/update/<int:id>/', views.UpdateAccount.as_view(), name='account_update'),
]

distribution/urls.py
from django.urls import path
from . import views

app_name = "distribution"

urlpatterns = [
    path("allocate/<int:food_id>/", views.allocate_distribution, name='allocate_distribution'),
    path("list/", views.DistributionList.as_view(), name='list'),

    path("clear/<int:distribution_id>/", views.clear_distribution, name="clear"),
    path("cleared/pdf/generate/<int:distribution_id>/", views.cleared_distribution_pdf, name="cleared_pdf"),
]

food/urls.py
from django.urls import path
from . import views

app_name = "food"

urlpatterns = [
    path("create/", views.CreateFood.as_view(), name="create"),
    path("detail/<int:pk>/", views.FoodDetail.as_view(), name="detail"),
    path("list/", views.FoodList.as_view(), name="list"),
    path("update/<int:pk>/", views.UpdateFood.as_view(), name="update"),
    path("delete/<int:pk>/", views.DeleteFood.as_view(), name="delete"),
    path("delete/success.html", views.success_delete_food, name="success_delete"),

    path("deposit/<int:food_id>/", views.IncreaseReserves.as_view(), name='increase_reserves'),
    path("deposit/success/<int:food_id>/", views.success_increase_reserves, name='success_increase_reserve'),

    path('unit/list/', views.DistributionUnitList.as_view(), name='unit_list'),
    path('unit/detail/<int:pk>/', views.DistributionUnitDetail.as_view(), name='unit_detail'),
    path('unit/create/', views.CreateDistributionUnit.as_view(), name='unit_create'),
    path('unit/update/<int:id>/', views.UpdateDistributionUnit.as_view(), name='unit_update'),
    path('unit/delete/<int:pk>/', views.DeleteDistributionUnit.as_view(), name='unit_delete'),
    path('unit/delete/success.html', views.success_delete_food_unit, name='success_delete_unit')
]

refugee/urls.py
from django.urls import path
from . import views

app_name = "refugee"

urlpatterns = [
    path("create/", views.CreateRefugee.as_view(), name="create"),
    path("detail/<int:pk>/", views.RefugeeDetail.as_view(), name="detail"),
    path("list/", views.RefugeeList.as_view(), name="list"),
    path("list/pdf/generate/", views.refugee_list_pdf, name="list_pdf"),
    path("update/<int:pk>/", views.UpdateRefugee.as_view(), name="update"),
    path("delete/<int:pk>/", views.DeleteRefugee.as_view(), name="delete"),
    path("delete/success.html", views.success_delete_refugee, name="success_delete"),
]

refugee_system/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('account.urls')),
    path('food/', include('food.urls')),
    path('refugee/', include('refugee.urls')),
    path('distribution/', include('distribution.urls')),
]

templates/base_dashboard.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Meta -->
    <meta name="description" content="{{ site_description }}">
    <meta name="author" content="{{ site_author }}">

    <title>{{ site_title }}</title>

    <!-- vendor css -->
    <link href="{% static 'lib/font-awesome/css/font-awesome.css' %}" rel="stylesheet">
    <link href="{% static 'lib/Ionicons/css/ionicons.css' %}" rel="stylesheet">
    <link href="{% static 'lib/perfect-scrollbar/css/perfect-scrollbar.css' %}" rel="stylesheet">
    <link href="{% static 'lib/jquery-switchbutton/jquery.switchButton.css' %}" rel="stylesheet">

    <!-- Bracket CSS -->
    <link rel="stylesheet" href="{% static 'css/bracket.css' %}">

{#      datatables stylesheets#}
  <link href="{% static 'lib/datatables/jquery.dataTables.css' %}" rel="stylesheet">
{#      select2 stylesheet#}
    <link rel="stylesheet" href="{% static 'lib/select2/css/select2.min.css' %}">
  </head>

  <body>

    <!-- ########## START: LEFT PANEL ########## -->
    <div class="br-logo"><a href=""><span>[</span>{{ site_title }}<span>]</span></a></div>
    <div class="br-sideleft overflow-y-auto">
      <label class="sidebar-label pd-x-15 mg-t-20">Navigation</label>
      <div class="br-sideleft-menu">
        <a href="{% url 'index' %}" class="br-menu-link">
          <div class="br-menu-item">
            <i class="menu-item-icon icon ion-ios-home-outline tx-22"></i>
            <span class="menu-item-label">Dashboard</span>
          </div><!-- menu-item -->
        </a><!-- br-menu-link -->
        {% if perms.food.custom_can_add_food %}
        <a href="{% url 'food:list' %}" class="br-menu-link">
          <div class="br-menu-item">
            <i class="menu-item-icon icon ion-ios-filing-outline tx-24"></i>
            <span class="menu-item-label">Food and Resources</span>
          </div><!-- menu-item -->
        </a><!-- br-menu-link -->
          {% endif %}
        {% if perms.distribution.can_allocate_distribution %}
        <a href="{% url 'food:unit_list' %}" class="br-menu-link">
          <div class="br-menu-item">
            <i class="menu-item-icon icon ion-ios-filing-outline tx-24"></i>
            <span class="menu-item-label">Distribution Units</span>
          </div><!-- menu-item -->
        </a><!-- br-menu-link -->
          {% endif %}
        {% if perms.distribution.can_clear_distribution %}
        <a href="{% url 'distribution:list' %}" class="br-menu-link">
          <div class="br-menu-item">
            <i class="menu-item-icon icon ion-ios-filing-outline tx-24"></i>
            <span class="menu-item-label">Distribution</span>
          </div><!-- menu-item -->
        </a><!-- br-menu-link -->
        {% endif %}
        {% if perms.refugee.custom_can_add_refugee %}
        <a href="{% url 'refugee:list' %}" class="br-menu-link">
          <div class="br-menu-item">
            <i class="menu-item-icon ion-ios-people tx-24"></i>
            <span class="menu-item-label">Refugees </span>
          </div><!-- menu-item -->
        </a><!-- br-menu-link -->
        {% endif %}
        {% if perms.accounts.custom_can_add_user %}
        <a href="{% url 'account:register_user' %}" class="br-menu-link">
          <div class="br-menu-item">
              <i class="fa fa-user"></i>
            <span class="menu-item-label">Register System User </span>
          </div><!-- menu-item -->
        </a><!-- br-menu-link -->
        {% endif %}
      </div><!-- br-sideleft-menu -->

      <label class="sidebar-label pd-x-15 mg-t-25 mg-b-20 tx-info op-9">Information Summary</label>

      <div class="info-list">
        <div class="d-flex align-items-center justify-content-between pd-x-15">
          <div>
            <p class="tx-10 tx-roboto tx-uppercase tx-spacing-1 tx-white op-3 mg-b-2 space-nowrap">Number of Refugees</p>
            <h5 class="tx-lato tx-white tx-normal mg-b-0">{{ num_refugees }}</h5>
          </div>
        </div><!-- d-flex -->

        <div class="d-flex align-items-center justify-content-between pd-x-15 mg-t-20">
          <div>
            <p class="tx-10 tx-roboto tx-uppercase tx-spacing-1 tx-white op-3 mg-b-2 space-nowrap">Number of Supervisors</p>
            <h5 class="tx-lato tx-white tx-normal mg-b-0">{{ num_agents }}</h5>
          </div>
        </div><!-- d-flex -->

        <div class="d-flex align-items-center justify-content-between pd-x-15 mg-t-20">
          <div>
            <p class="tx-10 tx-roboto tx-uppercase tx-spacing-1 tx-white op-3 mg-b-2 space-nowrap">Food Types Available</p>
            <h5 class="tx-lato tx-white tx-normal mg-b-0">{{ num_foods }}</h5>
          </div>
        </div><!-- d-flex -->

        <div class="d-flex align-items-center justify-content-between pd-x-15 mg-t-20">
          <div>
            <p class="tx-10 tx-roboto tx-uppercase tx-spacing-1 tx-white op-3 mg-b-2 space-nowrap">Number of Distribution</p>
            <h5 class="tx-lato tx-white tx-normal mg-b-0">{{ num_distribution }}</h5>
          </div>
        </div><!-- d-flex -->
      </div><!-- info-lst -->

      <br>
    </div><!-- br-sideleft -->
    <!-- ########## END: LEFT PANEL ########## -->

    <!-- ########## START: HEAD PANEL ########## -->
    <div class="br-header">
      <div class="br-header-left">
        <div class="navicon-left hidden-md-down"><a id="btnLeftMenu" href=""><i class="icon ion-navicon-round"></i></a></div>
        <div class="navicon-left hidden-lg-up"><a id="btnLeftMenuMobile" href=""><i class="icon ion-navicon-round"></i></a></div>
        <div class="input-group hidden-xs-down wd-170 transition">
          <input id="searchbox" type="text" class="form-control" placeholder="Search">
          <span class="input-group-btn">
            <button class="btn btn-secondary" type="button"><i class="fa fa-search"></i></button>
          </span>
        </div><!-- input-group -->
      </div><!-- br-header-left -->
      <div class="br-header-right">
        <nav class="nav">
          <div class="dropdown">
            <a href="" class="nav-link nav-link-profile" data-toggle="dropdown">
              <span class="logged-name hidden-md-down">{{ request.user.get_full_name }}</span>
              <img src="{% static 'media' %}/{{ request.user.account.picture }}" class="wd-32 rounded-circle" alt="">
              <span class="square-10 bg-success"></span>
            </a>
            <div class="dropdown-menu dropdown-menu-header wd-200">
              <ul class="list-unstyled user-profile-nav">
                <li><a href="{% url 'account:profile' %}"><i class="icon ion-ios-person"></i> Edit Profile</a></li>
                <li><a href="{% url 'password_change' %}"><i class="icon ion-ios-gear"></i> Change Password</a></li>
                <li><a href="{% url 'logout' %}"><i class="icon ion-power"></i> Sign Out</a></li>
              </ul>
            </div><!-- dropdown-menu -->
          </div><!-- dropdown -->
        </nav>

      </div><!-- br-header-right -->
    </div><!-- br-header -->
    <!-- ########## END: HEAD PANEL ########## -->

    {% block content %}
    
    {% endblock %}

    <script src="{% static 'lib/jquery/jquery.js' %}"></script>
    <script src="{% static 'lib/popper.js/popper.js' %}"></script>
    <script src="{% static 'lib/bootstrap/bootstrap.js' %}"></script>
    <script src="{% static 'lib/perfect-scrollbar/js/perfect-scrollbar.jquery.js' %}"></script>
    <script src="{% static 'lib/moment/moment.js' %}"></script>
    <script src="{% static 'lib/jquery-ui/jquery-ui.js' %}"></script>
    <script src="{% static 'lib/jquery-switchbutton/jquery.switchButton.js' %}"></script>
    <script src="{% static 'lib/peity/jquery.peity.js' %}"></script>
    <script src="{% static 'lib/jquery.sparkline.bower/jquery.sparkline.min.js' %}"></script>
    <script src="{% static 'lib/d3/d3.js' %}"></script>


    <script src="{% static 'js/bracket.js' %}"></script>
    <script src="{% static 'js/ResizeSensor.js' %}"></script>
    <script src="{% static 'js/dashboard.js' %}"></script>
    <script>
      $(function(){
        'use strict'

        // FOR DEMO ONLY
        // menu collapsed by default during first page load or refresh with screen
        // having a size between 992px and 1299px. This is intended on this page only
        // for better viewing of widgets demo.
        $(window).resize(function(){
          minimizeMenu();
        });

        minimizeMenu();

        function minimizeMenu() {
          if(window.matchMedia('(min-width: 992px)').matches && window.matchMedia('(max-width: 1299px)').matches) {
            // show only the icons and hide left menu label by default
            $('.menu-item-label,.menu-item-arrow').addClass('op-lg-0-force d-lg-none');
            $('body').addClass('collapsed-menu');
            $('.show-sub + .br-menu-sub').slideUp();
          } else if(window.matchMedia('(min-width: 1300px)').matches && !$('body').hasClass('collapsed-menu')) {
            $('.menu-item-label,.menu-item-arrow').removeClass('op-lg-0-force d-lg-none');
            $('body').removeClass('collapsed-menu');
            $('.show-sub + .br-menu-sub').slideDown();
          }
        }
      });
    </script>


  {% block scripts %}

  {% endblock %}


  </body>
</html>

templates/base_messages.html
{% load static %}
<!DOCTYPE html>
<html lang="en" class="pos-relative">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Meta -->
    <meta name="description" content="{{ site_description }}">
    <meta name="author" content="{{ site_author }}">

    <title>{{ site_title }}</title>

    <!-- vendor css -->
    <link href="{% static 'lib/font-awesome/css/font-awesome.css' %}" rel="stylesheet">
    <link href="{% static 'lib/Ionicons/css/ionicons.css' %}" rel="stylesheet">

    <!-- Bracket CSS -->
    <link rel="stylesheet" href="{% static 'css/bracket.css' %}">
  </head>

  <body class="pos-relative">

    <div class="ht-100v d-flex align-items-center justify-content-center">
      <div class="wd-lg-70p wd-xl-50p tx-center pd-x-40">
          {% block content %}
          
          {% endblock %}
      </div>
    </div><!-- ht-100v -->

    <script src="{% static 'lib/jquery/jquery.js' %}"></script>
    <script src="{% static 'lib/popper.js/popper.js' %}"></script>
    <script src="{% static 'lib/bootstrap/bootstrap.js' %}"></script>

  </body>
</html>

templates/index.html
{% extends 'base_dashboard.html' %}

{% block content %}
    <!-- ########## START: MAIN PANEL ########## -->
    <div class="br-mainpanel">
      <div class="pd-30">
        <h4 class="tx-gray-800 mg-b-5">Dashboard</h4>
        <p class="mg-b-0">Welcome to {{ site_title }} portal. Here you can manage various aspects of the system according to your privileges.</p>
      </div><!-- d-flex -->

      <div class="br-pagebody mg-t-5 pd-x-30">
        <div class="row row-sm">
          <div class="col-sm-6 col-xl-3">
            <div class="bg-teal rounded overflow-hidden">
              <div class="pd-25 d-flex align-items-center">
                <i class="ion ion-earth tx-60 lh-0 tx-white op-7"></i>
                <div class="mg-l-20">
                  <p class="tx-10 tx-spacing-1 tx-mont tx-medium tx-uppercase tx-white-8 mg-b-10">Today's Distributions</p>
                  <p class="tx-24 tx-white tx-lato tx-bold mg-b-2 lh-1">1,975,224</p>
                </div>
              </div>
            </div>
          </div><!-- col-3 -->
          <div class="col-sm-6 col-xl-3 mg-t-20 mg-sm-t-0">
            <div class="bg-danger rounded overflow-hidden">
              <div class="pd-25 d-flex align-items-center">
                <i class="ion ion-bag tx-60 lh-0 tx-white op-7"></i>
                <div class="mg-l-20">
                  <p class="tx-10 tx-spacing-1 tx-mont tx-medium tx-uppercase tx-white-8 mg-b-10">Successful Distributions</p>
                  <p class="tx-24 tx-white tx-lato tx-bold mg-b-2 lh-1">{{ successful_distributions }}</p>
                </div>
              </div>
            </div>
          </div><!-- col-3 -->
          <div class="col-sm-6 col-xl-3 mg-t-20 mg-xl-t-0">
            <div class="bg-primary rounded overflow-hidden">
              <div class="pd-25 d-flex align-items-center">
                <i class="ion ion-monitor tx-60 lh-0 tx-white op-7"></i>
                <div class="mg-l-20">
                  <p class="tx-10 tx-spacing-1 tx-mont tx-medium tx-uppercase tx-white-8 mg-b-10">Total Refugees</p>
                  <p class="tx-24 tx-white tx-lato tx-bold mg-b-2 lh-1">{{ num_refugees }}</p>
                </div>
              </div>
            </div>
          </div><!-- col-3 -->
          <div class="col-sm-6 col-xl-3 mg-t-20 mg-xl-t-0">
            <div class="bg-br-primary rounded overflow-hidden">
              <div class="pd-25 d-flex align-items-center">
                <i class="ion ion-clock tx-60 lh-0 tx-white op-7"></i>
                <div class="mg-l-20">
                  <p class="tx-10 tx-spacing-1 tx-mont tx-medium tx-uppercase tx-white-8 mg-b-10">Total Agents</p>
                  <p class="tx-24 tx-white tx-lato tx-bold mg-b-2 lh-1">{{ num_agents }}</p>
                </div>
              </div>
            </div>
          </div><!-- col-3 -->
        </div><!-- row -->

        <div class="row row-sm mg-t-20">
          <div class="col-8">

            <div class="card bd-0 shadow-base pd-30 mg-t-20">
              <div class="d-flex align-items-center justify-content-between mg-b-30">
                <div>
                  <h6 class="tx-13 tx-uppercase tx-inverse tx-semibold tx-spacing-1">Newly Registered Refugees</h6>
                </div>
                <a href="" class="btn btn-outline-info btn-oblong tx-11 tx-uppercase tx-mont tx-medium tx-spacing-1 pd-x-30 bd-2">See more</a>
              </div><!-- d-flex -->

              <table class="table table-valign-middle mg-b-0">
                <tbody>

                {% for refugee in refugee_latest %}
                  <tr>
                    <td class="pd-l-0-force">
                      <img src="http://via.placeholder.com/280x280" class="wd-40 rounded-circle" alt="{{ refugee.name }}">
                    </td>
                    <td>
                      <h6 class="tx-inverse tx-14 mg-b-0">{{ refugee.name }}</h6>
                      <span class="tx-12">{{ refugee.telephone }}</span>
                    </td>
                    <td>{{ refugee.date_time_registered }}</td>
                    <td><span id="sparkline1">{{ refugee.gender }}</span></td>
                    <td class="pd-r-0-force tx-center"><a href="#" class="tx-gray-600"><i class="icon ion-more tx-18 lh-0"></i></a></td>
                  </tr>
                {% endfor %}
                </tbody>
              </table>
            </div><!-- card -->

            <div class="card shadow-base card-body pd-25 bd-0 mg-t-20">
              <div class="row">
                <div class="col-sm-12">
                  <h6 class="card-title tx-uppercase tx-12">Distribution Success Rate</h6>
                  <p class="display-4 tx-medium tx-inverse mg-b-5 tx-lato">{{ distribution_rate }}%</p>
                  <div class="progress mg-b-10">
                    <div class="progress-bar bg-primary progress-bar-xs wd-30p" role="progressbar" aria-valuenow="{{ distribution_rate }}" aria-valuemin="0" aria-valuemax="100"></div>
                  </div><!-- progress -->
                  <p class="tx-12">This figure show total allocations against number which has been collected.</p>
                  <p class="tx-11 lh-3 mg-b-0">You can also use other progress variants..</p>
                </div><!-- col-6 -->
              </div><!-- row -->
            </div><!-- card -->


          </div><!-- col-9 -->
          <div class="col-4">


            <div class="card bd-0 shadow-base pd-30">
              <h6 class="tx-13 tx-uppercase tx-inverse tx-semibold tx-spacing-1">Server Status</h6>
              <p class="mg-b-25">Summary of the status of your server.</p>

              <label class="tx-12 tx-gray-600 mg-b-10">CPU Usage (40.05 - 32 cpus)</label>
              <div class="progress ht-5 mg-b-10">
                <div class="progress-bar wd-25p" role="progressbar" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
              </div>

              <label class="tx-12 tx-gray-600 mg-b-10">Memory Usage (32.2%)</label>
              <div class="progress ht-5 mg-b-10">
                <div class="progress-bar bg-teal wd-60p" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100"></div>
              </div>

              <label class="tx-12 tx-gray-600 mg-b-10">Disk Usage (82.2%)</label>
              <div class="progress ht-5 mg-b-10">
                <div class="progress-bar bg-danger wd-70p" role="progressbar" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100"></div>
              </div>

              <label class="tx-12 tx-gray-600 mg-b-10">Databases (63/100)</label>
              <div class="progress ht-5 mg-b-10">
                <div class="progress-bar bg-warning wd-50p" role="progressbar" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"></div>
              </div>

              <label class="tx-12 tx-gray-600 mg-b-10">Domains (30/50)</label>
              <div class="progress ht-5 mg-b-10">
                <div class="progress-bar bg-info wd-45p" role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100"></div>
              </div>

              <label class="tx-12 tx-gray-600 mg-b-10">Email Account (13/50)</label>
              <div class="progress ht-5 mg-b-10">
                <div class="progress-bar bg-purple wd-65p" role="progressbar" aria-valuenow="65" aria-valuemin="0" aria-valuemax="100"></div>
              </div>

              <div class="mg-t-20 tx-13">
                <a href="" class="tx-gray-600 hover-info">Generate Report</a>
                <a href="" class="tx-gray-600 hover-info bd-l mg-l-10 pd-l-10">Print Report</a>
              </div>
            </div><!-- card -->

          </div><!-- col-3 -->
        </div><!-- row -->

      </div><!-- br-pagebody -->
      <footer class="br-footer">
        <div class="footer-left">
          <div class="mg-b-2">Copyright &copy; 2018. {{ site_author }}. All Rights Reserved.</div>
          <div>Attentively and carefully made by {{ site_author }}.</div>
        </div>
        <div class="footer-right d-flex align-items-center">
          <span class="tx-uppercase mg-r-10">Follow:</span>
          <a target="_blank" class="pd-x-5" href="https://github.com/jerryshikanga/"><i class="fa fa-github tx-20"></i></a>
          <a target="_blank" class="pd-x-5" href="https://linkedin.com/in/jerryshikanga/"><i class="fa fa-linkedin tx-20"></i></a>
        </div>
      </footer>
    </div><!-- br-mainpanel -->
    <!-- ########## END: MAIN PANEL ########## -->
{% endblock %}